### ISSUE TITLE
Add compression level control for PNG

### ISSUE THREAD

**Issue by kannes** [nextgis/qgis_qtiles#86] opened 2017-09-19 07:09 UTC
For JPG tiles you can set the quality for a compromise between image quality and file size.

As PNG is lossless (unless you alter things apriori) there is no such control. It would be nice to be able to set the compression rate though. This is a balance between smaller size and slower creation. From what I know, decompression speed is not affected.

Compressing the tiles from QTiles after rendering easily saves 50-75% of space if I recall my tests correctly.

**Comment by StacktraceException** [comment] 2023-06-21 13:21
no, the current best image format is JPEG XL for a multitude of reasons. Among which is also the best compression ratio for both lossy and lossless images. png and jpeg are legacy outdated formats. they are  unacceptable in 2023.

**Comment by kannes** [comment] 2023-06-22 18:19
> no, the current best image format is JPEG XL for a multitude of reasons. Among which is also the best compression ratio for both lossy and lossless images. png and jpeg are legacy outdated formats. they are unacceptable in 2023.

No one asked for your offtopic opinion. Learn some manners and stop posting crap like this all over the place. This is not a random forum.

**Comment by dezhin** [comment] 2023-10-05 21:40
Closed as a duplicate of #79

**Closed by dezhin** 2023-10-05 21:40 UTC
Labels: enhancement

**Comment by kannes** [comment] 2023-10-06 07:03
Huh, I'd say it's the other way around?

The other issue asked for a feature that makes little sense (PNG has no *quality* setting). I made this one to request an option to set the *compression* level, which has effects on processing time and file size, but changes nothing in regards to image *quality*.

**Comment by dezhin** [comment] 2023-10-06 19:01
It's only about liberalism. It's obvious that we should have quality for JPEG and compression level for PNG. That issue just the first and we don't need two for this feature.
